{
    "openapi": "3.0.0",
    "info": {
        "title": "API Tugas UKK Peminjaman Alat",
        "description": "Dokumentasi API Sistem Peminjaman Alat",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://127.0.0.1:8000",
            "description": "Local Development Server"
        }
    ],
    "paths": {
        "/api/alats": {
            "get": {
                "tags": [
                    "Alat"
                ],
                "summary": "Ambil semua alat",
                "operationId": "f470cd39e062976fd8cc4640a5ffec03",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "data": [
                                        {
                                            "id": 1,
                                            "kode": "SPA00001",
                                            "nama": "Laptop Asus",
                                            "kategori_alat_id": 1,
                                            "stok": 10,
                                            "status": "tersedia",
                                            "created_at": "2026-02-20T10:00:00.000000Z",
                                            "updated_at": "2026-02-20T10:00:00.000000Z"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Alat"
                ],
                "summary": "Tambah alat",
                "operationId": "cee032e444fa7cbb4008d2913a4c9c6f",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "nama"
                                ],
                                "properties": {
                                    "nama": {
                                        "type": "string",
                                        "example": "Laptop Asus"
                                    },
                                    "kategori_alat_id": {
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "foto": {
                                        "type": "string",
                                        "format": "binary"
                                    },
                                    "stok": {
                                        "type": "integer",
                                        "example": 10
                                    },
                                    "status": {
                                        "type": "string",
                                        "example": "tersedia"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Berhasil menambahkan alat",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Alat berhasil ditambahkan",
                                    "data": {
                                        "id": 1,
                                        "kode": "SPA00001",
                                        "nama": "Laptop Asus",
                                        "kategori_alat_id": 1,
                                        "stok": 10,
                                        "status": "tersedia"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/alats/{id}": {
            "get": {
                "tags": [
                    "Alat"
                ],
                "summary": "Ambil detail alat",
                "operationId": "bcfc23533cdefb0a466b66900ebb385b",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail alat",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "data": {
                                        "id": 1,
                                        "kode": "SPA00001",
                                        "nama": "Laptop Asus",
                                        "kategori_alat_id": 1,
                                        "stok": 10,
                                        "status": "tersedia",
                                        "created_at": "2026-02-20T10:00:00.000000Z",
                                        "updated_at": "2026-02-20T10:00:00.000000Z"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Alat"
                ],
                "summary": "Hapus alat",
                "operationId": "0e5369eb7e4db53e021c99634b6217f3",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil hapus alat",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Alat berhasil dihapus"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Alat"
                ],
                "summary": "Update alat",
                "operationId": "bc19c4d905a23bb2d1ce87bcaac115fc",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "nama": {
                                        "type": "string",
                                        "example": "Laptop Asus Update"
                                    },
                                    "stok": {
                                        "type": "integer",
                                        "example": 5
                                    },
                                    "status": {
                                        "type": "string",
                                        "example": "maintenance"
                                    },
                                    "kategori_alat_id": {
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "foto": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Berhasil update alat",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Alat berhasil diperbarui"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/dashboard/stats": {
            "get": {
                "tags": [
                    "Dashboard"
                ],
                "summary": "Ambil statistik untuk dashboard",
                "operationId": "97f93f93be9753e12dfa48ed63db092c",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil statistik dashboard"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/pengembalians": {
            "get": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Ambil semua data pengembalian",
                "operationId": "42183678d877f85754c07865a1ddcd8d",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data pengembalian",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "data": [
                                        {
                                            "id": 1,
                                            "peminjaman_id": 1,
                                            "tanggal_dikembalikan": "2026-02-24 13:42:29",
                                            "kondisi_kembali": "baik",
                                            "catatan": "Kembali dalam keadaan utuh",
                                            "peminjaman": {
                                                "id": 1,
                                                "kode": "PINJAM-00001",
                                                "peminjam": {
                                                    "id": 1,
                                                    "name": "User Name"
                                                },
                                                "alat": {
                                                    "id": 1,
                                                    "nama": "Laptop Asus"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Catat pengembalian baru (bisa via Scan QR/Kode atau ID)",
                "operationId": "32dce95d56188ba79bca47d8979f9b0d",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "kode_peminjaman": {
                                        "description": "Wajib jika peminjaman_id kosong",
                                        "type": "string",
                                        "example": "PINJAM-00001"
                                    },
                                    "peminjaman_id": {
                                        "description": "Wajib jika kode_peminjaman kosong",
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "kondisi_kembali": {
                                        "type": "string",
                                        "enum": [
                                            "baik",
                                            "rusak",
                                            "hilang"
                                        ],
                                        "example": "baik"
                                    },
                                    "catatan": {
                                        "type": "string",
                                        "example": "Alat kembali lengkap"
                                    },
                                    "foto": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Alat berhasil dikembalikan",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Alat berhasil dikembalikan.",
                                    "data": {
                                        "id": 1,
                                        "peminjaman_id": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/pengembalians/{id}": {
            "get": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Ambil detail pengembalian",
                "operationId": "e9ff8f71fbde44a90b35c3c6ebecfc8d",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail pengembalian"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Hapus data pengembalian (Membatalkan pengembalian)",
                "operationId": "23714bc20a300d7783ca7d50445dee9a",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data pengembalian berhasil dihapus"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Update data pengembalian",
                "operationId": "64018b6b52a2751765506e0d115d8a78",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "kondisi_kembali": {
                                        "type": "string",
                                        "enum": [
                                            "baik",
                                            "rusak",
                                            "hilang"
                                        ]
                                    },
                                    "catatan": {
                                        "type": "string"
                                    },
                                    "tanggal_dikembalikan": {
                                        "type": "string",
                                        "format": "date-time"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Data pengembalian berhasil diupdate"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/pengembalians/trashed": {
            "get": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Ambil data pengembalian yang dihapus (Trash)",
                "operationId": "134ee048215ed055312d7688eb9a496f",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data trashed"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/pengembalians/{id}/restore": {
            "post": {
                "tags": [
                    "Pengembalian"
                ],
                "summary": "Kembalikan data pengembalian yang dihapus",
                "operationId": "5b8cd00dd191dd54690f02c7fa4c2c53",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data berhasil di-restore"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "operationId": "c5e838284c7f343f0e5e5fd589161c96",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "example": "admin@admin.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "admin123"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login berhasil",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "user": {
                                            "type": "object"
                                        },
                                        "token": {
                                            "type": "string",
                                            "example": "1|extytasuppi123!"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Email atau password salah"
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "operationId": "399284ae5e84627c95a691127018a412",
                "responses": {
                    "200": {
                        "description": "Logout berhasil",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "Logout berhasil"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/master-data/kategori-alat": {
            "get": {
                "tags": [
                    "Master Data - Kategori Alat"
                ],
                "summary": "Ambil semua kategori alat",
                "operationId": "dcd2adf08c9f08cae6dc2e9db6ae2d42",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data"
                    }
                }
            },
            "post": {
                "tags": [
                    "Master Data - Kategori Alat"
                ],
                "summary": "Tambah kategori alat",
                "operationId": "31207c07d57b6e359ed06675140a316e",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "nama_kategori_alat"
                                ],
                                "properties": {
                                    "nama_kategori_alat": {
                                        "type": "string",
                                        "example": "Elektronik"
                                    },
                                    "status": {
                                        "type": "string",
                                        "example": "active"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Berhasil menambahkan kategori"
                    }
                }
            }
        },
        "/api/master-data/kategori-alat/active": {
            "get": {
                "tags": [
                    "Master Data - Kategori Alat"
                ],
                "summary": "Ambil kategori alat dengan status active",
                "operationId": "e1d993edd2c88cba8cfaa292177f9f6d",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data kategori active"
                    }
                }
            }
        },
        "/api/master-data/kategori-alat/{id}": {
            "delete": {
                "tags": [
                    "Master Data - Kategori Alat"
                ],
                "summary": "Hapus kategori alat",
                "operationId": "f295b74af1e664706f2a363c1fa04696",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil hapus kategori"
                    }
                }
            },
            "patch": {
                "tags": [
                    "Master Data - Kategori Alat"
                ],
                "summary": "Update kategori alat",
                "operationId": "d7c666b4739167b19dbe1a9ac8ba257e",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID kategori",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "nama_kategori_alat"
                                ],
                                "properties": {
                                    "nama_kategori_alat": {
                                        "type": "string",
                                        "example": "Elektronik Update"
                                    },
                                    "status": {
                                        "type": "string",
                                        "example": "inactive"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Berhasil update kategori"
                    }
                }
            }
        },
        "/api/peminjamans": {
            "get": {
                "tags": [
                    "Peminjaman"
                ],
                "summary": "Ambil semua data peminjaman",
                "operationId": "0900f747fceb68f3ec3ee8a723071c86",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data peminjaman",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "data": [
                                        {
                                            "id": 1,
                                            "kode": "PINJAM-00001",
                                            "peminjam_id": 1,
                                            "alat_id": 1,
                                            "tanggal_pinjam": "2026-02-23",
                                            "status": "Dipinjam",
                                            "peminjam": {
                                                "id": 1,
                                                "name": "User Name"
                                            },
                                            "alat": {
                                                "id": 1,
                                                "nama": "Laptop Asus",
                                                "foto": "image.jpg"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Peminjaman"
                ],
                "summary": "Buat peminjaman baru",
                "operationId": "977544c8f330c5e7c0e112d53ef75209",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "alat_id",
                                    "peminjam_id"
                                ],
                                "properties": {
                                    "alat_id": {
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "peminjam_id": {
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "tanggal_pinjam": {
                                        "type": "string",
                                        "format": "date",
                                        "example": "2026-02-23"
                                    },
                                    "status": {
                                        "type": "string",
                                        "example": "Dipinjam"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Peminjaman berhasil dibuat",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Peminjaman berhasil dicatat",
                                    "data": {
                                        "id": 1,
                                        "kode": "PINJAM-00001"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/peminjamans/{id}": {
            "get": {
                "tags": [
                    "Peminjaman"
                ],
                "summary": "Ambil detail peminjaman",
                "operationId": "e4635fb5e7e5bdfe823bad05508718f9",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail peminjaman",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "data": {
                                        "id": 1,
                                        "kode": "PINJAM-00001",
                                        "peminjam": {
                                            "id": 1,
                                            "name": "User Name"
                                        },
                                        "alat": {
                                            "id": 1,
                                            "nama": "Laptop Asus",
                                            "foto": "image.jpg"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Peminjaman"
                ],
                "summary": "Hapus/Batalkan peminjaman (Kembalikan stok)",
                "operationId": "7c86fce857dbadd78f9f225f4a8fe86b",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data peminjaman berhasil dihapus",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Data peminjaman dihapus"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Peminjaman"
                ],
                "summary": "Update data peminjaman",
                "operationId": "2e4f763c4211551101a96a07e40654b8",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "tanggal_pinjam": {
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "status": {
                                        "type": "string",
                                        "enum": [
                                            "Dipinjam",
                                            "Terlambat",
                                            "Dikembalikan"
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Data peminjaman berhasil diperbarui",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "status": "success",
                                    "message": "Data peminjaman berhasil diperbarui"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Alat",
            "description": "API untuk mengelola data alat"
        },
        {
            "name": "Pengembalian",
            "description": "API untuk mengelola transaksi pengembalian alat"
        },
        {
            "name": "Master Data - Kategori Alat",
            "description": "API untuk mengelola kategori alat"
        },
        {
            "name": "Peminjaman",
            "description": "API untuk mengelola transaksi peminjaman dan pengembalian alat"
        },
        {
            "name": "Dashboard",
            "description": "Dashboard"
        },
        {
            "name": "Auth",
            "description": "Auth"
        }
    ]
}